llm-pi-ai:
  providers:
    nr:
      displayName: nr
      apiKeyEnv: NR_API_KEY
      api: openai-completions
      baseURL: https://litellm.jereh.cn
      models:
        - id: Jereh-DeepSeek-V4-Flash-0731
          name: Jereh-DeepSeek-V4-Flash-0731
agent-default-model:
  provider: nr
  model: Jereh-DeepSeek-V4-Flash-0731
