#!/usr/bin/env python3
# Build-time patch: make noVNC's vnc.html load the aio desktop-fit scripts.
#
# Two tags are appended before </body>, in this order:
#   vnc-config.js   generated by the entrypoint at startup; sets
#                   window.__DSH_RESIZE_ENDPOINT__ when RESIZE_ENDPOINT is
#                   configured (empty file otherwise). Must come first so
#                   fit-resize.js sees the global.
#   fit-resize.js   the debounced viewport -> desktop-size writer.
#
# Strip-then-insert rather than "skip if already present": Dockerfile.prod.layered
# builds on an existing aio image whose vnc.html may already carry an OLDER
# tag set, and a skip-if-present guard would silently keep the stale one.
import re
import sys

PATH = sys.argv[1] if len(sys.argv) > 1 else '/usr/share/novnc/vnc.html'
VERSION = '4'
TAGS = (f'<script src="vnc-config.js?v={VERSION}"></script>'
        f'<script src="fit-resize.js?v={VERSION}"></script>')

html = open(PATH, encoding='utf-8').read()
html = re.sub(r'<script src="(?:vnc-config|fit-resize)\.js[^"]*"></script>', '', html)
if '</body>' not in html:
    raise SystemExit(f'{PATH}: no </body> to anchor the fit-resize tags')
open(PATH, 'w', encoding='utf-8').write(html.replace('</body>', TAGS + '</body>', 1))
print(f'patched {PATH} (v{VERSION})')
